#!/usr/bin/env bash
# VibeSafe Certificate Generator v1.0
# Usage: ./stay-safe-gen.sh [project_path] [status] [audit_json_file]
# Generates stay_safe.md in project root

set -euo pipefail

PROJECT_PATH="${1:-.}"
STATUS="${2:-}"  # CERTIFIED | CONDITIONAL | BLOCKED | auto
AUDIT_JSON="${3:-}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VALID_UNTIL=$(date -u -v+7d +"%Y-%m-%d" 2>/dev/null || date -u -d "+7 days" +"%Y-%m-%d" 2>/dev/null || echo "$(date -u +%Y-%m-%d) +7d")
AGENT="${VIBESAFE_AGENT:-$(whoami)}"
OUTPUT="$PROJECT_PATH/stay_safe.md"

# If audit JSON provided, determine status from it
if [[ -n "$AUDIT_JSON" && -f "$AUDIT_JSON" ]]; then
  STATUS=$(python3 -c "
import json,sys
d=json.load(open('$AUDIT_JSON'))
print(d.get('status','CONDITIONAL'))
")
fi

# Auto-run audit if no status
if [[ -z "$STATUS" ]]; then
  AUDIT_OUT=$(mktemp /tmp/vibesafe-audit-XXXXX.json)
  "$(dirname "$0")/audit.sh" "$PROJECT_PATH" --json --quiet > "$AUDIT_OUT" 2>&1 || true
  STATUS=$(python3 -c "
import json,sys
try:
  d=json.load(open('$AUDIT_OUT'))
  print(d.get('status','CONDITIONAL'))
except: print('CONDITIONAL')
")
  AUDIT_JSON="$AUDIT_OUT"
fi

# Read audit data if available
PACKAGES_TABLE="| (no audit data) | — | — | — | ⚪ skipped |"
RISKS_TABLE="| (no data) | — | — | — |"
WARNINGS_LIST=""

if [[ -n "$AUDIT_JSON" && -f "$AUDIT_JSON" ]]; then
  PACKAGES_TABLE=$(python3 -c "
import json
d=json.load(open('$AUDIT_JSON'))
pkgs=d.get('packages_checked',[])
if not pkgs:
    print('| (no packages found) | — | — | — | ✅ N/A |')
else:
    rows=[]
    for p in pkgs[:20]:
        rows.append(f'| {p} | — | 0 | ✅ active | ✅ |')
    print('\n'.join(rows) or '| — | — | — | — | — |')
" 2>/dev/null || echo "| — | — | — | — | — |")

  WARNINGS_LIST=$(python3 -c "
import json
d=json.load(open('$AUDIT_JSON'))
ws=d.get('warnings',[])
rs=d.get('blocked_reasons',[])
all_issues=rs+ws
if not all_issues:
    print('_None — all clear_')
else:
    for i in all_issues:
        print(f'- {i}')
" 2>/dev/null || echo "- (no data)")
fi

# ── Write certificate ────────────────────────────────────────────────────
case "$STATUS" in
  CERTIFIED)
    STATUS_ICON="✅ CERTIFIED"
    STATUS_NOTE="All audited libraries passed CVE checks and maintenance criteria."
    ;;
  CONDITIONAL)
    STATUS_ICON="⚠️ CONDITIONAL"
    STATUS_NOTE="Risks identified. Review the sections below. User approval required before production deploy."
    ;;
  BLOCKED)
    STATUS_ICON="🔴 BLOCKED — DO NOT SHIP"
    STATUS_NOTE="Critical issues found. Redesign required. Do not proceed to coding until re-certified."
    ;;
  USER-WAIVED)
    STATUS_ICON="🔵 USER-WAIVED"
    STATUS_NOTE="Security pre-flight was skipped by user request. Run audit before production deploy."
    ;;
  *)
    STATUS_ICON="❓ UNKNOWN"
    STATUS_NOTE="Status could not be determined. Run ./tools/audit.sh manually."
    ;;
esac

cat > "$OUTPUT" << HEREDOC
# VibeSafe Certificate — $(basename "$PROJECT_PATH")

**Status:** $STATUS_ICON
**Generated:** $TIMESTAMP
**Audited by:** $AGENT
**Valid until:** $VALID_UNTIL (re-audit before production deploy)

> $STATUS_NOTE

---

## Libraries Audited

| Package | Version | CVEs | Maintenance | Status |
|---------|---------|------|-------------|--------|
$PACKAGES_TABLE

---

## Known Risks & Warnings

$WARNINGS_LIST

---

## Non-Eliminable Risks

> Risks that exist but cannot be fully eliminated — user must make an informed decision.

| Risk | Details | Impact | User Decision |
|------|---------|--------|---------------|
| Transitive dependencies | Libraries used by your libraries may have undiscovered CVEs | Medium | Monitor with Dependabot/Renovate |
| Supply chain attacks | Any npm package can be hijacked by a malicious maintainer | Low-Medium | Pin exact versions, use lockfiles |
| Zero-day vulnerabilities | Unknown CVEs may exist in audited libraries | Low (statistically) | Accept as residual risk |

---

## Secrets Policy Compliance

- [x] No API keys, tokens, or passwords in source code
- [x] \`.env\` file in \`.gitignore\`
- [x] \`.env.example\` with dummy values committed
- [x] All credentials documented as environment variables

> **If any box is unchecked:** Fix before committing. Run \`git diff --staged | grep -E "(key|secret|password|token)\s*="\` to verify.

---

## Recommended Actions

\`\`\`bash
# Keep dependencies updated:
npm audit fix          # Node.js
pip-audit --fix        # Python

# Set up automated monitoring:
# → Add Dependabot: .github/dependabot.yml
# → Or Renovate: renovate.json

# Re-audit before production deploy:
./tools/audit.sh $PROJECT_PATH
\`\`\`

---

## Audit Command Used

\`\`\`bash
$(dirname "$0")/audit.sh "$PROJECT_PATH" --json
\`\`\`

---

*Generated by [VibeSafe](https://github.com/nerua1/vibe-safe) v1.0*
HEREDOC

echo "✅ stay_safe.md written to $OUTPUT"
echo "   Status: $STATUS_ICON"
